### ISSUE TITLE
Rarities format in README is missing Alternate Art Shorthand?

### ISSUE THREAD

**Issue by bergerab** [the-fab-cube/flesh-and-blood-cards#189]
Hi @luceleaftea . First 🙏 thank you for this incredible project. 

I was trying to parse the rarity of cards, and I found some cards that don't follow the format found in the README. One example of this is Iyslander who's card rarities are:

P – HER052 – N, M – EVR120 – F, T – UPR103 – N, V – UPR103 – N – AA, V – UPR103 – N – FA

The README says if a rarity changed, it uses this format:

```
{Rarity Shorthand separated by spaces} - {Card Identifier} - {Set Edition Shorthand}
```

But the 4th and 5th rarities for Iyslander seem to be of the format:

```
{Rarity Shorthand separated by spaces} - {Card Identifier} - {Set Edition Shorthand} (- {Altered Art Shorthand})
```

Can there also be foil printings included in the rarity? I assume it is possible that a foil card could be more rare than a non foil, just as an altered art Iyslander can be more rare than the standard

**Comment by luceleaftea** [comment]
Hey, nice catch on the documentation miss! You're correct, if the rarity changes mid-printing or there are multiple rarity versions of the same card in the set, the full correlation is to the `{Card Identifier} - {Set Edition Shorthand} (- {Altered Art Shorthand}` portion. (Essentially in this case, the Rarity field mirrors what's in the Variations field to denote which rarity each Variation is.)

Because of the aforementioned one-to-one association with the Variations field, the foiling data in that field is what applies to the associated rarity, which covers cases like Iyslander, who has the Marvel Cold Foil variation that shares a set code with her normal non-foil Token rarity variation.

I'll fix up the README, and this should be a lot easier to parse in the near future when I release the big update that adds JSON format to the repo that will have a lot of this parsing/associating done for you!

Thanks for pointing this out!
