### ISSUE TITLE
`Image URLs` column in `card.csv` has inconsistent formatting

### ISSUE THREAD

**Issue by dcollinsn** [the-fab-cube/flesh-and-blood-cards#191]
The `Image URLs` column in card.csv has inconsistent formatting which frustrates parsing:

- A mix of hypens and dashes are used to separate the URL from the metadata fields
- Some entries have multiple spaces after the separating comma
- Some entries have no space after the separating comma

This forces the use `re.split()` to parse this field instead of the `str` method `.split()`, which is slower, and also requires the user to guess all of the ways in which the data may be inconsistently formatted.

**Comment by luceleaftea** [comment]
I actually have an update coming very soon (hopefully this week!) which makes JSON the primary method for consuming data (although CSV will always be an option, since CSV will be used for data entry still). So that should hopefully remove this frustration! But thank you for bringing it up, it's one of the reasons I've been making this big JSON update.

You can see the open PR here - it should be relatively stable but I can't guarantee it won't change until it's fully merged into main: https://github.com/the-fab-cube/flesh-and-blood-cards/pull/183

Fixing the hyphen / dash issue is something that I will still need to tackle for anyone who still wants to use the CSVs, so I'll leave this issue open still :)

**Comment by dcollinsn** [comment]
@luceleaftea , what is the "original" form of the data going to be? Is it going to be a CSV that you use a script to convert to JSON, or JSON that you use a script to convert to CSV, or something else that you use a script to convert to both formats?

I can probably submit a PR that will clean up some issues with the CSV (which you might use, for example, as a pre-commit hook), but there's no need to do so if the CSVs will be generated from some other format.

**Comment by luceleaftea** [comment]
@dcollinsn the flow will be CSV -> JSON! Data entry will be done through the CSVs, and JSON will be generated from that.
